# Generated by Django 5.0.2 on 2024-03-09 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource_id', models.CharField(default='fac950c0-00d5-4ec1-a4d3-9cbebf98a305', max_length=100)),
                ('filters', models.JSONField(blank=True, null=True)),
                ('search', models.TextField()),
                ('distinct', models.BooleanField(default=True)),
                ('plain', models.BooleanField(default=False)),
                ('language', models.CharField(default='english', max_length=30)),
                ('limit', models.IntegerField(default=10)),
                ('offset', models.IntegerField(default=0)),
                ('fields', models.JSONField(blank=True, null=True)),
                ('sort', models.JSONField(blank=True, null=True)),
                ('include_total', models.BooleanField(default=False)),
                ('records_format', models.CharField(choices=[('objects', 'objects'), ('lists', 'lists'), ('csv', 'csv'), ('tsv', 'tsv')], default='csv', max_length=7)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='query', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
