# Generated by Django 5.0.2 on 2024-04-07 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_query_fields_alter_query_filters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='name',
            field=models.CharField(default='My Query', max_length=100),
        ),
    ]
